---
name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - DocumentAPI
          - UserAPI

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for ${{ matrix.service }}
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]'):latest"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME ./${{ matrix.service }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]'):latest
